apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra-config
  namespace: paywall-dev
data:
  hydra.yaml: |
    version: v2.2.0

    dsn: postgres://paywall:paywall_dev@postgres:5432/hydra?sslmode=disable

    serve:
      public:
        base_url: http://auth.paywall.local
        cors:
          enabled: true
          allowed_origins:
            - http://paywall.local
            - http://auth.paywall.local
            - http://login.paywall.local
      admin:
        base_url: http://hydra:4445

    urls:
      self:
        issuer: http://auth.paywall.local
      login: http://login.paywall.local/login
      consent: http://login.paywall.local/consent
      logout: http://login.paywall.local/logout
      error: http://login.paywall.local/error
      post_logout_redirect: http://paywall.local/

    strategies:
      access_token: jwt

    ttl:
      access_token: 1h
      refresh_token: 720h
      id_token: 1h
      auth_code: 10m
      login_consent_request: 1h

    oauth2:
      expose_internal_errors: false
      allowed_top_level_claims: []

    log:
      level: info
      format: text
      leak_sensitive_values: false

    secrets:
      system:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

    dev: true
