apiVersion: v1
kind: Service
metadata:
  name: kratos
  namespace: paywall-dev
  labels:
    app: kratos
spec:
  type: ClusterIP
  selector:
    app: kratos
  ports:
    - name: public
      port: 4433
      targetPort: 4433
      protocol: TCP
    - name: admin
      port: 4434
      targetPort: 4434
      protocol: TCP
