apiVersion: v1
kind: Service
metadata:
  name: kratos-ui
  namespace: paywall-dev
  labels:
    app: kratos-ui
spec:
  type: ClusterIP
  selector:
    app: kratos-ui
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
