apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paywall-dev

resources:
  - namespace.yaml
  - postgres/secret.yaml
  - postgres/configmap.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - ory/kratos-config.yaml
  - ory/kratos-deployment.yaml
  - ory/kratos-service.yaml
  - ory/hydra-config.yaml
  - ory/hydra-deployment.yaml
  - ory/hydra-service.yaml
  - ory/kratos-ui-deployment.yaml
  - ory/kratos-ui-service.yaml
  - ory/mailslurper-deployment.yaml
  - ory/mailslurper-service.yaml
  - ory/oidc-client-job.yaml
  - paywall/backend-deployment.yaml
  - paywall/backend-service.yaml
  - paywall/frontend-deployment.yaml
  - paywall/frontend-service.yaml
